### ISSUE TITLE
[BUG] - Unable to set boolean struct parameters to false due to Golang's JSON encoder

### ISSUE THREAD

**Issue by Static-Flow** [vultr/govultr#114]
**Describe the bug**
This is sort of a bug, sort of an issue with Golang as a whole. In Golang's JSON encoder, when encoding a struct with a bool parameter which also has the "omitempty" tag, any bool fields set to false are dropped. This is the case with all the structs in govultr. This has the effect that you cannot actually send requests to the api with false values as they get dropped. A discussion of the issue can be found here golang/go#13284.

**To Reproduce**

```
instanceOptions := &govultr.InstanceCreateReq{
    Plan:                 "vc2-4c-8gb",
    Region:               "dfw",
    AppID:                37,
    ActivationEmail: false
}
byt,err := json.Marshal(instanceOptions) 
fmt.Println(string(byt))

Output: {"region":"dfw","plan":"vc2-4c-8gb","app_id":37}
```

**Expected behavior**
`{"region":"dfw","plan":"vc2-4c-8gb","activation_email":false}`

The two solutions are either switch out all bool fields for *bool or drop the omitempty tag from all bool fields. Switching to bool pointers is probably the way to go. I have a patch that switches them over if you'd like it but you may decide on a different course of action.

**Comment by ddymko** [comment]
@Static-Flow Yup, I am aware of the issue behavior with the encoder and missed patching the bools to pointers 👎. 

If you have a PR that changes these to pointers feel free to submit as this is what should have been done with the bools originally.
