### ISSUE TITLE
Example code in README incomplete

### ISSUE THREAD

**Issue by nobane** [vultr/govultr#127]
The example code should be a complete working example. Add an import for `golang.org/x/oauth2` and define `ctx`.

**Comment by lerichardson** [comment]
I'm pretty sure the code is took from govultr.go, which doesn't have an import for `golang.org/x/oauth2`. Plus, why would you really need a working example when you can just `go get github.com/vultr/govultr`

**Comment by nobane** [comment]
Providing broken or incomplete examples can lead to confusion, especially among newer developers.

It seems kind of strange to me to have broken or incomplete examples posted, especially given the caliber of this library (I find it quite good).

The examples helped me get up and going using this library, and its been working great. That said, nearly every Go project I've encountered that provides an example. provides a complete one. 

The other example is also broken as well, `var instances []govultr.Instance` is declared but never used. 

With how much effort has clearly been put into this library, I would hope to see some complete (as in copy & paste & go) examples.

**Comment by lerichardson** [comment]
So are you simply asking them to copy/paste code from `govultr.go`? What code would they choose? It simply seems irrelevant and too complicated, considering that `govultr.go` is 240 lines. Copy/pasting functions seems useless because it would be hard to understand anyways without knowing the variables. What code would you want them to add?

**Comment by nobane** [comment]
I am just asking to add/change a few lines to make the examples function as-is without having to figure out what to add or fix in them.

**Comment by nobane** [comment]
```package main

import (
  "context"
  "os"
  "golang.org/x/oauth2"
  "github.com/vultr/govultr/v2"
)

func main() {
  apiKey := os.Getenv("VultrAPIKey")

  config := &oauth2.Config{}
  ctx := context.Background()
  ts := config.TokenSource(ctx, &oauth2.Token{AccessToken: apiKey})
  vultrClient := govultr.NewClient(oauth2.NewClient(ctx,ts))

  // Optional changes
  _ = vultrClient.SetBaseURL("https://api.vultr.com")
  vultrClient.SetUserAgent("mycool-app")
  vultrClient.SetRateLimit(500)
}```

**Comment by nobane** [comment]
I think having snippets of examples is okay, but please have them not be broken. It's just confusing. So remove `var instances []govultr.Instance` from the pagination example.

**Comment by lerichardson** [comment]
I just don't think it's big enough of a deal to make a PR. If you want to take a deeper look, just look at the code
