### ISSUE TITLE
I can't use it

### ISSUE THREAD

**Issue by rendaoer** [vultr/govultr#154]
![截屏2021-08-04 下午6 22 05](https://user-images.githubusercontent.com/46780118/128165824-7c0d6843-ecd1-4a77-b484-f5c10ecf330d.png)
<img width="1082" alt="截屏2021-08-04 下午6 24 23" src="https://user-images.githubusercontent.com/46780118/128165833-2463c77f-1e7e-450f-96e0-543becf5e1db.png">
I wrote it according to the example, but it reports this error

**Comment by rendaoer** [comment]
in MacBook Air m1 arm

**Comment by ddymko** [comment]
@rendaoer I just tested this locally and it is running fine. Also you are running your application without issue the error you are getting looks like the API calls are failing.

Looking at your screenshot it
https://user-images.githubusercontent.com/46780118/128165824-7c0d6843-ecd1-4a77-b484-f5c10ecf330d.png

If you are putting your API Key in `os.Getenv()` this will not work as this call looks for a ENV Var.

**Comment by rendaoer** [comment]
Thank you, I was negligent and didn't check it carefully
