### ISSUE TITLE
[BUG] - Tags specified in the InstanceCreateReq are not actually added

### ISSUE THREAD

**Issue by ribtoks** [vultr/govultr#226]
**Describe the bug**

I'm creating an instance using the library like this:

```
instanceOptions := &govultr.InstanceCreateReq{
	Tags:     []string{"my-fancy-tag-here"},    // <-----------------------------
	OsID:     instanceOSID,
	Plan:     instancePlan,
	Region:   instanceRegion,
	UserData: userdata,
}

_, err := vultr.Instance.Create(context.Background(), instanceOptions)
return err
```

Later in the Vultr panel the instance is running, but does not have any tags attached to it. OS, Region and UserData are correct, on the other hand.

**To Reproduce**

(previous section)

**Expected behavior**

Instances have tags in the UI and for real (are expected to be available for further filtering etc.)

**Screenshots**
N/A

**Desktop (please complete the following information where applicable:**
 - OS: Any
 - Language Version: Go 1.17
 - Browser N/A
 - Version: v2.17.1 of the repository

**Additional context**

N/A

**Comment by ddymko** [comment]
@ribtoks When i create an instance with tags they show up on the UI just fine?


Using govultr (which makes interacts with the API) sets and returns the tags 

```go
	instanceOptions := &govultr.InstanceCreateReq{
		Tags:   []string{"my-fancy-tag-here", "my-fancy-tag-her2e", "my-fancy-tag-her3e"}, // <-----------------------------
		OsID:   270,
		Plan:   "vc2-1c-1gb",
		Region: "ewr",
	}
	data, err := vc.Instance.Create(context.Background(), instanceOptions)
	if err != nil {
		panic(err)
	}

	fmt.Println(data.Tags)

	data1, err := vc.Instance.Get(context.Background(), data.ID)
	if err != nil {
		panic(err)
	}

	fmt.Println(data1.Tags)
```

Output

```
/private/var/folders/r9/ds0snrl541g64b14_pnkzy4r0000gn/T/GoLand/___go_build_github_com_vultr_govultr_v2_cmd
[my-fancy-tag-her2e my-fancy-tag-her3e my-fancy-tag-here]
[my-fancy-tag-her2e my-fancy-tag-her3e my-fancy-tag-here]
```

The tags also do appear on the UI
![Screen Shot 2022-06-04 at 6 47 52 AM](https://user-images.githubusercontent.com/1588386/171995861-daede655-4d53-4ce5-a251-a93f0e3c2e1f.png)


I believe the UI team is working on implementing the filter feature tags as that is currently missing.

**Comment by ribtoks** [comment]
@ddymko Thank you for fast response. I'm not yet sure what is going wrong as my code looks exactly the same (except plan `vc2-1c-1gb`, os id `387` and region `fra`. Thank you again for checking. I will try to reproduce more.

**Comment by ribtoks** [comment]
@ddymko Ok, now I see. It only works if I add 2 tags and more. With 1 tag in the array it did not work.

**Comment by ddymko** [comment]
@ribtoks hmmmm even with 1 Tag in the array it works

![Screen Shot 2022-06-04 at 7 12 21 AM](https://user-images.githubusercontent.com/1588386/171996574-b17f072e-5114-4d67-b66d-59d12a08fc33.png)

![Screen Shot 2022-06-04 at 7 13 23 AM](https://user-images.githubusercontent.com/1588386/171996580-8f2bfd07-ee78-4851-acdb-4cf04307e893.png)

**Comment by ribtoks** [comment]
@ddymko Thank you for checking. I will report if there will be anything new on my side.

**Comment by ribtoks** [comment]
Closing the issue as it started to work now. In the meantime I updated the go module, maybe the bug was in the older version or it was a transient issue on the backend.
