### ISSUE TITLE
[Feature] - Support iPXE chain URL in BareMetalCreate

### ISSUE THREAD

**Issue by neilmock** [vultr/govultr#237]
**Is your feature request related to a problem? Please describe.**
We'd like to boot bare metal servers using iPXE via the API, and it doesn't seem to be supported.

**Describe the solution you'd like**
An IPXEChainURL field under BareMetalCreate

**Describe alternatives you've considered**
I've considered submitting a pull request (!) if I'm missing that this is actually supported somehow.

**Comment by neilmock** [comment]
I just realized this isn't supported via the REST API unless I'm missing something.

**Comment by optik-aper** [comment]
@neilmock Yeah, that is only supported in VPS instances via the API.  It's potentially something that can be supported though so we'll look into it.

**Comment by neilmock** [comment]
@optik-aper I was misunderstanding how to do this, but it is possible by creating a script, which is totally fine and not really needed at the API level I don't think.
