### ISSUE TITLE
Support for Vultr VPC v2

### ISSUE THREAD

**Issue by 2000yeshu** [vultr/govultr#265]
When will the VPC v2 support be released. I can see that it has been developed and present in master.
As it has become default for newer clusters. I want to use the api with [machine-controller](https://github.com/kubermatic/machine-controller).

**Comment by optik-aper** [comment]
Hello @2000yeshu!  Support for VPC2 went in to [3.3.0](https://github.com/vultr/govultr/releases).  There is some additional functionality for the VPC2s added in 3.3.1 as well.  Is that what you need?

**Comment by 2000yeshu** [comment]
Yes, that's exactly what i want. Thanks for pointing me.
