### ISSUE TITLE
I would like to rent vps, from Vultr, Ionos, Hetzner and Contabo. In each vps of each company.

### ISSUE THREAD

**Issue by Wotan6891** [vultr/govultr#275]
I would like to rent vps, from Vultr, Ionos, Hetzner and Contabo. In each vps of each company have the same web application, any changes are synchronized.

This way if one VPS fails, the other will not fail, I can also organize them depending on the location. And also in case a vps reaches 80% of its resources, another vps already designated will immediately come to its rescue.

Do you know of any software to do this?

**Comment by optik-aper** [comment]
Hello @Wotan6891 That's probably a better question for [Vultr Support](https://www.vultr.com/support/).
