### ISSUE TITLE
[BUG] - IPV6 info struct is different to the doc

### ISSUE THREAD

**Issue by jiekun** [vultr/govultr#304]
**Describe the bug**
As described in the API doc: https://www.vultr.com/api/#tag/instances/operation/list-instances , the data structure of IPV6 related fields is an array.
<img width="706" alt="image" src="https://github.com/vultr/govultr/assets/30280396/d885fd3a-d3aa-4f96-a986-5c654e954671">

Currently, govultr using 3 flat fields:
https://github.com/vultr/govultr/blob/5125e02e715ae6eb3ce854f0e7116c7ce545a710/instance.go#L98

**Comment by optik-aper** [comment]
It looks like the docs are old and incorrect based on what's coming out of the API:
![image](https://github.com/vultr/govultr/assets/8485770/30442736-69f1-4273-9028-4a8d36b39771)

**Comment by jiekun** [comment]
Thank you for the confirmation.
